<a href="https://colab.research.google.com/github/Aditi31kapil/Cognitive_Computing/blob/main/Cognitive(4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ques 1

In [3]:
import numpy as np

arr = [1,2,3,4,5]
np_arr = np.array(arr)
print(np_arr)

[1 2 3 4 5]


In [8]:
#Add
add = np_arr + 2
print(add)

#Mul
mult = np_arr * 2
print(mult)

#Div
div = np_arr / 2
print(div)

[ 7.  8.  9. 10. 11.]
[10. 12. 14. 16. 18.]
[2.5 3.  3.5 4.  4.5]


Ques 2

In [14]:
#a
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])
#b
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

print(np.bincount(x).argmax())
print(np.bincount(y).argmax())


[5 4 6 3 2 1]
1
1


Ques 3

In [16]:
arr= np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[0][1])
print(arr[2][0])

20
70


Ques 4

Diff between Resize and Reshape And Transpose

| Feature | Reshape | Resize | Transpose |
|---|---|---|---|
| **Purpose** | Changes the shape of an array without changing its data. | Changes the shape and size of an array. It repeats or truncates elements to fit the new size. | Flips the dimensions of an array. Rows become columns, and columns become rows. |
| **Data Modification** | Does not modify the original data. | Might add or remove elements to match the new size. | Does not modify the original data, only rearranges it. |
| **Element Count** | The total number of elements remains the same. | The total number of elements might change. | The total number of elements remains the same. |
| **In the Context of Images** | Changes the dimensions of the image (e.g., height and width) without altering pixel data. | Changes the dimensions of the image, potentially adding or removing pixels. | Flips the image along its diagonal, swapping width and height. |
| **Example** | `arr.reshape(2, 3)` | `np.resize(arr, (3, 3))` | `arr.T` |

In [27]:
arr = np.linspace(10,100,25)
print("array", arr)

#attributes
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Dimensions:", arr.ndim)

#Transpose
print("Transpose:", arr.T)
reshaped = arr.reshape(5,5)
print("Reshaped:", reshaped)
print("Transpose:", reshaped.T)

array [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape: (25,)
Size: 25
Data Type: float64
Dimensions: 1
Transpose: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Reshaped: [[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]
Transpose: [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


Ques 5

In [23]:
arr= [10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35]
ucs420_aditi = np.array(arr)
reshaped = ucs420_aditi.reshape(3,4)
print(reshaped)
#stats
print('------------------------------------------')
print("Mean:", np.mean(reshaped))
print("Median:", np.median(reshaped))
print("Unique:", np.unique(reshaped))
print("Minimum:", np.min(reshaped))
print("Maximum:", np.max(reshaped))
print("Variance:", np.var(reshaped))
print("Standard Deviation:", np.std(reshaped))

print('------------------------------------------')
reshaped_ucs420_aditi = reshaped.reshape(4,3)
print(reshaped_ucs420_aditi)
print('------------------------------------------')
resized_ucs420_aditi = np.resize(reshaped_ucs420_aditi, (2,3))
print(resized_ucs420_aditi)


[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
------------------------------------------
Mean: 43.333333333333336
Median: 37.5
Unique: [10 15 20 30 35 40 50 60 70 80 90]
Minimum: 10
Maximum: 90
Variance: 651.3888888888889
Standard Deviation: 25.522321385189258
------------------------------------------
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
------------------------------------------
[[10 20 30]
 [40 50 60]]
